name: Post market news to Facebook

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * 1-5'  # Weekdays EU open (07:30 UTC)
    - cron: '0 13 * * 1-5'  # Weekdays US pre-market (13:00 UTC)
    - cron: '0 20 * * 1-5'  # Weekdays US close/evening (20:00 UTC)
    - cron: '0 11 * * 6'    # Saturday weekly recap (11:00 UTC)
    - cron: '0 18 * * 0'    # Sunday week-ahead (18:00 UTC)

concurrency:
  group: fb-market-news
  cancel-in-progress: true

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Post to Facebook
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
        run: python scripts/post_news.py

