name: Post market news to Facebook

on:
  schedule:
    - cron: "0 9,18 * * *"   # runs 09:00 & 18:00 UTC daily (change if you like)
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
  run: |
    python -m pip install --upgrade pip
    python -m pip install requests feedparser python-dateutil

      - name: Run poster
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
        run: |
          python scripts/post_news.py
